Update readme.md
neo-project/neo-express pull request #414
Opened 2023-12-06 09:56 UTC by Celia18305

Update out-of-date descriptions.

2023-12-06 12:50 UTC, cschuchardt88 requested changes

2023-12-06 13:38 UTC, cschuchardt88 commented
Can you take out all the stuff talking about Legacy version(s).

2023-12-07 08:32 UTC, Celia18305 commented
I removed all "Neo Legacy" content. Please kindly check.

2023-12-07 09:31 UTC, cschuchardt88 approved these changes

2023-12-07 16:12 UTC, Liaojinghui commented on readme.md
> +> Note: .NET 6 Arm64 has [full support for Apple Silicon](https://devblogs.microsoft.com/dotnet/announcing-net-6/#arm64).
this is still .net 6 right?

2023-12-10 23:01 UTC, Liaojinghui approved these changes

2023-12-10 23:01 UTC, merged