New command: contract storage update
neo-project/neo-express pull request #434
Opened 2024-03-27 19:29 UTC by meevee98

Also had to move `contract storage` to `contract storage get` because there are conflicts in the arguments with the new command

2024-04-01 15:35 UTC, melanke requested changes

2024-04-01 15:35 UTC, melanke commented on src/neoxp/Commands/ContractCommand.Storage.cs
>          [Command(Name = "storage", Description = "Display storage for specified contract")]
I think this description needs to be updated

2024-04-02 21:30 UTC, melanke commented on src/neoxp/Commands/ContractCommand.Storage.cs
>          [Command(Name = "storage", Description = "Display storage for specified contract")]
Resolved

2024-04-02 21:31 UTC, melanke approved these changes
Fine by me. But I am not an anthority to approve on this repo 😅

2024-04-02 21:48 UTC, lock9 commented
Hi @Jim8y ,

Can you check this, please? 

Thanks

2024-04-02 23:39 UTC, Jim8y approved these changes

2024-04-02 23:39 UTC, merged