No submodule
neo-project/neo-express pull request #464
Opened 2024-08-23 06:30 UTC by chenzhitong

2024-08-23 06:39 UTC, chenzhitong commented
@cschuchardt88 Please review

2024-08-23 14:40 UTC, Jim8y approved these changes

2024-08-24 22:31 UTC, cschuchardt88 requested changes

2024-08-24 22:31 UTC, cschuchardt88 commented on src/bctklib/bctklib.csproj
> +        <PackageReference Include="Neo" Version="3.7.6" />
```suggestion
        <PackageReference Include="Neo" Version="$(NeoVersion)" />
```

2024-08-24 22:31 UTC, cschuchardt88 commented on src/Directory.Build.props
> +        <NeoVersion>3.7.5</NeoVersion>
```suggestion
        <NeoVersion>3.7.6</NeoVersion>
```

2024-08-24 22:48 UTC, cschuchardt88 approved these changes

2024-08-24 22:49 UTC, merged